const web = {
  head: "web development",
  projects: [
    {
      name: "Kotam Landing Page",
      date: "2019-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "HTMLCSS",
      coverImg: "/imgs/works/web/kotam.PNG",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#e68ded",
    },
    {
      name: "book shop",
      date: "2019-9-1",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "PureJs",
      coverImg: "/imgs/works/web/bookstore.png",
      link: "",
      use:["html","css","javaScript","bootstarp"],
      bg: "#ee434c",
    },
    {
      name: "descover",
      date: "2019-5-2",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "PureJs",
      coverImg: "/imgs/works/web/discover.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#947155",
    },
    {
      name: "Clinical Landing Page",
      date: "2021-9-1",
      summury: "2021-9-1",
      techo: "ReactJs",
      coverImg: "/imgs/works/web/medical.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#4566f1",
    },
    {
      name: "ecommerce",
      date: "2022-2-2",
      summury: "2022-2-2",
      techo: "ReactJs",
      coverImg: "/imgs/works/web/komerce.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#28a745",
    },
    {
      name: "Corona live results",
      date: "2022-5-2",
      summury: "2022-5-2",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/korona.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#262c7c",
    },
    {
      name: "hotal landing page",
      date: "2019-10-2",
      summury: "2022-5-2",
      techo: "HTMLCSS",
      coverImg: "/imgs/works/web/kotal.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#3f4332",
    },
    {
      name: "old porfolio",
      date: "2022-5-2",
      summury: "2022-5-2",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/old.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#9e8c87",
    },
    {
      name: "weather app",
      date: "2022-5-2",
      summury: "2022-5-2",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/weather.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#5e3e20",
    },
    {
      name: "ko Gitbub",
      date: "2022-5-2",
      summury: "2022-5-2",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/kogit.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#6246ea",
    },
    {
      name: "quats",
      date: "2022-5-2",
      summury: "2022-5-2",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/quat.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#ffd56b",
    }   
  ],
  techarr: ["all", "HTMLCSS", "PureJs", "ReactJs", "ReactNodeJs"],
};
const excel = {
  head: "Excel",
  projects: [
    {
      name: "loll",
      date: "2020-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "GooglesheetForms",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "primary",
    },
    {
      name: "dalel",
      date: "",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "GooglesheetForms",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
      name: "jauice",
      date: "",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "GoogleSheet",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "info",
    },
    {
      name: "styudy",
      date: "ddddddddddddddddddddddddddddddd",
      summury: "",
      techo: "GoogleSheet",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "warning",
    },
  ],
  techarr: ["all", "GooglesheetForms", "GoogleSheet"],
};
const eng = {
  head: "Mecanical Design",
  projects: [
    {
      name: "mechanism",
      date: "2020-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "3DMax",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "primary",
    },
    {
      name: "car",
      date: "",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "AutoDesk",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
      name: "build",
      date: "",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "AutoCad",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "info",
    },
    {
      name: "prooo",
      date: "ddddddddddddddddddddddddddddddd",
      summury: "",
      techo: "Drawing",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "warning",
    },
  ],
  techarr: ["all", "Drawing", "AutoCad", "AutoDesk", "3DMax"],
};
export  {web , excel , eng}