const web = {
  head: "web development",
  projects: [
    {
      name: "photo graphic",
      date: "2019-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "HTMLCSS",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "primary",
    },
    {
      name: "book shop",
      date: "2019-5-1",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "PureJs",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
      name: "corona",
      date: "2022-1-2",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "ReactJs",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "info",
    },
    {
      name: "old portfolio",
      date: "2021-9-1",
      summury: "2021-9-1",
      techo: "ReactJs",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "warning",
    },
    {
      name: "ecommerce",
      date: "2022-2-2",
      summury: "2022-2-2",
      techo: "ReactJs",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "success",
    },
    {
      name: "new porfolio",
      date: "2022-5-2",
      summury: "2022-5-2",
      techo: "ReactNodeJs",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
        name: "aaaa",
        date: "2010-2-5",
        summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        techo: "HTMLCSS",
        coverImg: "",
        link: "",use:["html","css","javaScript","bootstarp"],
        bg: "primary",
      },
      {
        name: "bbbbb",
        date: "2011-2-5",
        summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        techo: "HTMLCSS",
        coverImg: "",
        link: "",use:["html","css","javaScript","bootstarp"],
        bg: "primary",
      },
      {
        name: "ccccc",
        date: "2012-2-5",
        summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        techo: "HTMLCSS",
        coverImg: "",
        link: "",use:["html","css","javaScript","bootstarp"],
        bg: "primary",
      },
      {
        name: "ddddddd",
        date: "2005-2-5",
        summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        techo: "HTMLCSS",
        coverImg: "",
        link: "",use:["html","css","javaScript","bootstarp"],
        bg: "primary",
      },
      {
        name: "abbb",
        date: "2015-2-5",
        summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        techo: "HTMLCSS",
        coverImg: "",
        link: "",use:["html","css","javaScript","bootstarp"],
        bg: "primary",
      },
  ],
  techarr: ["all", "HTMLCSS", "PureJs", "ReactJs", "ReactNodeJs"],
};
const excel = {
  head: "Excel",
  projects: [
    {
      name: "loll",
      date: "2020-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "GooglesheetForms",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "primary",
    },
    {
      name: "dalel",
      date: "",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "GooglesheetForms",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
      name: "jauice",
      date: "",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "GoogleSheet",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "info",
    },
    {
      name: "styudy",
      date: "ddddddddddddddddddddddddddddddd",
      summury: "",
      techo: "GoogleSheet",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "warning",
    },
  ],
  techarr: ["all", "GooglesheetForms", "GoogleSheet"],
};
const eng = {
  head: "Mecanical Design",
  projects: [
    {
      name: "mechanism",
      date: "2020-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "3DMax",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "primary",
    },
    {
      name: "car",
      date: "",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "AutoDesk",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
      name: "build",
      date: "",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "AutoCad",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "info",
    },
    {
      name: "prooo",
      date: "ddddddddddddddddddddddddddddddd",
      summury: "",
      techo: "Drawing",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "warning",
    },
  ],
  techarr: ["all", "Drawing", "AutoCad", "AutoDesk", "3DMax"],
};
export  {web , excel , eng}