const web = {
  head: "web development",
  projects: [
    {
      name: "kotam landing page",
      date: "2020-2-5",
      summury: "publish your work as a artist",
      techo: "HTMLCSS",
      coverImg: "/imgs/works/web/kotam.PNG",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#e68ded",
    },
    {
      name: "book shop",
      date: "2020-9-1",
      summury: "You can sell your book and expand your fan zone.",
      techo: "PureJs",
      coverImg: "/imgs/works/web/bookstore.png",
      link: "https://bostore.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#ee434c",
    },
    {
      name: "discover",
      date: "2020-5-2",
      summury: "know more about Egypt ✈.",
      techo: "PureJs",
      coverImg: "/imgs/works/web/discover.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#947155",
    },
    {
      name: "clinical landing page",
      date: "2020-12-1",
      summury: "reach your doctor and leave your pain.",
      techo: "ReactJs",
      coverImg: "/imgs/works/web/medical.png",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "#4566f1",
    },
    {
      name: "ecommerce",
      date: "2021-2-2",
      summury: "shopping become eaiser and funny.",
      techo: "ReactJs",
      coverImg: "/imgs/works/web/komerce.png",
      link: "https://koomercelive.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#28a745",
    },
    {
      name: "corona live results",
      date: "2021-5-2",
      summury: "stay home stay safe",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/korona.png",
      link: "https://cocoro.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#262c7c",
    },
    {
      name: "hotal landing page",
      date: "2021-10-2",
      summury: "book for holiday",
      techo: "HTMLCSS",
      coverImg: "/imgs/works/web/kotal.png",
      link: "https://kotmal.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#3f4332",
    },
    {
      name: "old porfolio",
      date: "2021-1-2",
      summury: ".",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/old.png",
      link: "https://khali3d.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#9e8c87",
    },
    {
      name: "weather app",
      date: "2022-4-2",
      summury: "you should konw weather state before leaving.",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/weather.png",
      link: "https://weatherfine.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#5e3e20",
    },
    {
      name: "ko Gitbub",
      date: "2022-3-2",
      summury: "save your usefull repo.",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/kogit.png",
      link: "https://kogit.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#6246ea",
    },
    {
      name: "quats",
      date: "2019-2-2",
      summury: "for fun",
      techo: "ReactNodeJs",
      coverImg: "/imgs/works/web/quat.png",
      link: "https://khaliedqouts.netlify.app/",
      use:["html","css","javaScript","bootstarp"],
      bg: "#ff884b",
    }   
  ],
  techarr: ["all", "HTMLCSS", "PureJs", "ReactJs", "ReactNodeJs"],
};
const excel = {
  head: "Excel",
  projects: [
    {
      name: "loll",
      date: "2020-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "GooglesheetForms",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "primary",
    },
    {
      name: "dalel",
      date: "",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "GooglesheetForms",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
      name: "jauice",
      date: "",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "GoogleSheet",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "info",
    },
    {
      name: "styudy",
      date: "ddddddddddddddddddddddddddddddd",
      summury: "",
      techo: "GoogleSheet",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "warning",
    },
  ],
  techarr: ["all", "GooglesheetForms", "GoogleSheet"],
};
const eng = {
  head: "Mecanical Design",
  projects: [
    {
      name: "mechanism",
      date: "2020-2-5",
      summury: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      techo: "3DMax",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "primary",
    },
    {
      name: "car",
      date: "",
      summury: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      techo: "AutoDesk",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "danger",
    },
    {
      name: "build",
      date: "",
      summury: "ccccccccccccccccccccccccccccccccccc",
      techo: "AutoCad",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "info",
    },
    {
      name: "prooo",
      date: "ddddddddddddddddddddddddddddddd",
      summury: "",
      techo: "Drawing",
      coverImg: "",
      link: "",use:["html","css","javaScript","bootstarp"],
      bg: "warning",
    },
  ],
  techarr: ["all", "Drawing", "AutoCad", "AutoDesk", "3DMax"],
};
export  {web , excel , eng}